xZetsubou/hass-localtuya

.github/workflows/tox.yaml, README.md, custom_components/localtuya/__init__.py, custom_components/localtuya/button.py, custom_components/localtuya/climate.py, custom_components/localtuya/common.py, custom_components/localtuya/config_flow.py, custom_components/localtuya/const.py, custom_components/localtuya/cover.py, custom_components/localtuya/helpers/templates.py, custom_components/localtuya/light.py, custom_components/localtuya/templates/sample_2g_switch.yaml, requirements_test.txt
```yaml
Templates:
The template is basically ready to go configs can be imported instead of choosing configs DPs names etc...
IMPORTANT: 
there is now valid check atm config so make sure you're importing correct configs.
the configs depends on the platform and what input does platform support read bottom.
THERE Is 2 ways to make template:
- 1st is write the yaml ur self:
[ Keep in mind there is no valid check atm ]
- 2st is to export ur device file from config flow. [ Recommended ]:
in HA Dashboard go to [ Devices -> localtuya -> Configure -> Edit Device * choose the device u want to export
Export the device config then submit]
Templates DIR:
the configs will be exported in [custom_components/localtuya/templates]
How to import:
-- When u add new device when the form [ Pick Entity type …
```
=> 2.1.0 Introduce templates

custom_components/localtuya/config_flow.py
Fix the auto protocol function stopped after first error.
Add product key locally if available, because Using Cloud API without pk will cause double entry updates due to updating keys.
=> Fix auto protocol function and productKey

custom_components/localtuya/pytuya/__init__.py
An error when control sub devices in protocols > 3.4
> Payload `data` was getting override with `dps: data` causing the to losing `CID`  in payload.
=> fix sub devices control for protocols > 3.4

custom_components/localtuya/button.py, custom_components/localtuya/climate.py, custom_components/localtuya/common.py, custom_components/localtuya/cover.py, custom_components/localtuya/fan.py, custom_components/localtuya/humidifier.py, custom_components/localtuya/light.py, custom_components/localtuya/switch.py, custom_components/localtuya/vacuum.py
* Remove initialization message from platforms and move it to `common.py`
* Remove: `dp_value_conf` and now `dp_value` can handle both dp index or config key dp
* Functions annotation
=> Refactor: entities initialization msg and remove dp_value_conf

custom_components/localtuya/__init__.py, custom_components/localtuya/common.py
* Setup API, Now execute in background without interrupt the initialization.
* Unloading platforms now get the platform from `hass.data.....[TUYA_DEVICES]` resolves #43 
On unloading: Platforms was pulled from `entry.data` this causing an error of `config entry was never loaded` because when we add first platform, `entry.data` would have the platform but it actually was never loaded since it first time added.
While we pull platforms from `TUYA_DEVICE` data we also store `close()` to call it after unload, instead of doing 2 loops.
=> Improve entry initialization

custom_components/localtuya/cloud_api.py, custom_components/localtuya/config_flow.py, custom_components/localtuya/core/pytuya/__init__.py
* DPS Data now will be pulled with devices data, data stored in `device_id` -> in `devices_list` with `dps_data` key.
* Adding new device DPS Data will be pulled from stored data `except the value!`
* Devices list in config flow now will be sorted: Starting from known devices first.
* Refresh cloud devices data when configure opened. `previously reload was needed in order to pull new devices data.`
* Handle the errors if refreshing token failed.
=> Improves config flow

custom_components/localtuya/config_flow.py, custom_components/localtuya/core/helpers.py, custom_components/localtuya/translations/en.json
* Templates list field are now insertable and searchable, so if you add templates new template into `templates` directory you can manually enter there name without need to load them up with HA boot.
* Templates names now will shows the same as filename with extension.
=> Templates manually enter the filenames

custom_components/localtuya/__init__.py, custom_components/localtuya/cloud_api.py, custom_components/localtuya/common.py, custom_components/localtuya/config_flow.py, custom_components/localtuya/const.py, custom_components/localtuya/diagnostics.py
* cloud_api now has async_connect function.
* Localtuya HASS Data is now stored as namedtuple `HassLocalTuyaData`
* Removed `TUYA_DEVICES`, `DATA_CLOUD` and `UNSUB LISTENERS`
* Sotred all unsub_callback in tuya_devices.unsub_listeners
* Reconnect if disconnected will be called after 2secounds.
=> * Refactor codes a little bit to make it easier to maintain.

custom_components/localtuya/__init__.py, custom_components/localtuya/services.yaml
example:
```yaml
service: localtuya.set_dp
data:
device_id: bf3e040669bd7aa117owie
value: 
- 1: false
- 2: true
- 3: true
```
=> Fix: `set dp service` and support multi list of set_dp

custom_components/localtuya/common.py, custom_components/localtuya/translations/en.json
* Fix: translations `username`
* Disconnected msg from "Warning" to "INFO"
=> Disconnected msg level and fix Translation `username`

custom_components/localtuya/common.py, custom_components/localtuya/switch.py
Fix: switch icon changes depends on state
=> Set `Switch` as default class for switches

custom_components/localtuya/fan.py, custom_components/localtuya/light.py, custom_components/localtuya/vacuum.py
Ref: 
https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation/
https://developers.home-assistant.io/blog/2023/12/19/constant-deprecation
closes #87
=> Update deprecated constants

custom_components/localtuya/core/tuya_devices/climates.py, custom_components/localtuya/discovery.py
1) I have a wifi socket that uses 3.1 tuya API protocol. It sends an unencrypted broadcast message. Without this fix, I can't create a device for my socket and see the following messages in the logs:
```
2024-01-04 19:16:18.227 DEBUG (MainThread) [custom_components.localtuya.discovery] Failed to decode bordcast from '192.168.1.190': b'\x00\x00U\xaa\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9f\x00\x00\x00\x00{"ip":"192.168.1.190","gwId":"04110747dc4f22865333","active":2,"ability":0,"mode":0,"encrypt":true,"productKey":"********","version":"3.1"}\x7f\xa5\xac\xec\x00\x00\xaaU'
```
2) `Fix climates plaform definitions` commit is a small fix from my previous findings
=> Skip decryption of broadcast message with UDP command

custom_components/localtuya/cover.py
Fixes an issue where commands are reversed (fz and zz), which causes the buttons in the cover entity to be unusable
=> Add option to switch Open/Close commands

custom_components/localtuya/light.py
**Brief:**
The minimum brightness value does not create a "range": it is only a limitation, e.g. by device capabilities. The range to be mapped is still (0, maximum). This also maps percentages to equal values between ranges.
**Long:**
HA UI for a Light entity provides brightness change slider expressed in percents. Actually, it does not allow to set 0%: the range is 1-100%. In automation and scripts, setting the brightness value to 0 is equal to turning off. This proves the concept that the minimum value has a special meaning, but does not create a "range".
With the  current brightness mapping, the percentage values are different in HA and SmartLife in 50 out of 100 cases. With the provided mapping, the percentage values are always equal.
I found only local use of `map_range`, and no use …
=> Fix LocalTuyaLight brightness mapping

custom_components/localtuya/core/pytuya/__init__.py
Sub-devices heartbeat loop might be in the `asyncio.sleep(HEARTBEAT_SUB_DEVICES_INTERVAL)`, or perform `subdevices_query()`, while the connection is already lost. Explicit `cancel()` call before other `clean_up_session()` actions resolves this issue.
This change is running in my HA for weeks, experienced a lot of disconnects, and never failed.
=> Explicit stop of sub-devices heartbeat

custom_components/localtuya/core/pytuya/__init__.py
Logically, we shall cleanup after connection lost, and only then notify the device. It was possible race condition, when `disconnected()` might start reconnect in a foreign loop. After the re-design, it is not a problem anymore. But better to keep the code safe.
=> First cleanup the connection, then notify the device

custom_components/localtuya/coordinator.py
Most of the time, sub-devices receive `disconnected()` due to their gateway has closed the connection. The subsequent reconnect is often instant, so that there is no a real need to call `self._shutdown_entities()`. Since all the async activity was re-implemented in the main thread, this call delays reconnection process. Compare:
<details>
<summary>Reconnect without delay for _shutdown_entities (709 ms)</summary>
```
2024-07-09 22:58:44.948 WARNING (MainThread) [custom_components.localtuya.coordinator] [bf5...whd - КЛ: Zigbee Bulb/G] Disconnected as gateway
2024-07-09 22:58:44.951 INFO (MainThread) [custom_components.localtuya.coordinator] [bf5...whd - КЛ: Zigbee Bulb] Disconnected
2024-07-09 22:58:44.952 INFO (MainThread) [custom_components.localtuya.coordinator] [bf2...ath - ГСЛ: Zigbee …
```
=> Don't invalidate sub-devices immediately

custom_components/localtuya/coordinator.py, custom_components/localtuya/core/pytuya/__init__.py
A connection for a sub-device is a connection to its gateway. No one of my gateways produce an error on request status or sending a command from/to offline sub-device. They silently accept commands and return cached status for hours. So, there is no a need to call `disconnected()` for a device that went offline: it just reconnects instantly, I didn't even see "unavailable" state for a moment in HA UI in tests with now commented out `disconnected()` call. Here is a log of such event:
<details>
<summary>Disconnect of offline device</summary>
```
2024-07-09 20:54:44.561 WARNING (MainThread) [custom_components.localtuya.coordinator] [bff...ns9 - ПЛ: Диммер] Sub-device is offline
2024-07-09 20:54:44.567 INFO (MainThread) [custom_components.localtuya.coordinator] [bff...ns9 - ПЛ: Диммер] …
```
=> Refactor Sub-Devices reconnecting task

custom_components/localtuya/coordinator.py, custom_components/localtuya/core/pytuya/__init__.py
After reading [your comment](https://github.com/xZetsubou/hass-localtuya/commit/a76f58ac948807e15f3b715de5147b583debf8bb#r144108583), I've analyzed the source code and found out, that:
- `transport_write()` without a delay is called only from `exchange()`.
- `exchange()` without a delay is called only from `status()`, always.
- `status()` is called only in two places:
https://github.com/xZetsubou/hass-localtuya/blob/a34e316448b5dd1762afee5b0c696016c5d756d9/custom_components/localtuya/coordinator.py#L231
https://github.com/xZetsubou/hass-localtuya/blob/a34e316448b5dd1762afee5b0c696016c5d756d9/custom_components/localtuya/core/pytuya/__init__.py#L1207
I can understand a need for sending requests without a delay only in the case of subsequent requests with no delay between them. So, I'm …
=> Eliminate no delay writes

custom_components/localtuya/core/pytuya/__init__.py
The last commit (2e2885042b16b8e17bfc95355b41850d70a9e80a) fixes a bug: a status from payload of a sub-device can be passed to its gateway. Though it is not a problem with fake gateways, which don't accept status changes, it's a big problem with real gateways. The examples are:
- a sub-device is attached to the gateway but not to LocalTuya;
- a sub-device is not added to the gateway's `sub_devices` list when the gateway is already connected (e.g. during LocalTuya current version start).
Tested in both cases, with BLE and ZIgbee sub-devices.
This is the last problem I found that prevented me to use real gateways in LocalTuya. Now I prefer and I'd recommend to add real gateways to LocalTuya, especially to those who has BLE devices.
By the way, I added some other small changes:
- comments …
=> Bug fix: status from a sub-device goes to its gateway

custom_components/localtuya/coordinator.py, custom_components/localtuya/core/pytuya/__init__.py, custom_components/localtuya/discovery.py
This pull request works better with [312](https://github.com/xZetsubou/hass-localtuya/pull/312), though it does not depend on it.
I intentionally made several commits, because most of them are not related to the main goal (which is 3b168dab6606bf3f04e3e1534f2367570baac8da). I'd suggest to read commit by commit, for easy understanding.
**Explanations:**
(e50ce752ad62065cf234e90bd7afbfc7a50817bf) I found it useful to tell messages produced by a fake gateway from messages produced by the same sub-device.
Heartbeat as itself is not required: a device closes inactive connection if there is no _any_ activity for some seconds. But having both heartbeat and sub-devices heartbeat provides additional load onto a gateway. I've made only one heartbeat, with the actual activity depending on whether it …
=> Refactor of making connections

custom_components/localtuya/__init__.py, custom_components/localtuya/coordinator.py, custom_components/localtuya/core/cloud_api.py, custom_components/localtuya/core/pytuya/__init__.py
Here it is. Now sub-devices offline, online and absent events are handled separately. In my tests I found out that if I remove a Zigbee subdevice without deleting its information, it keeps its cid even after connecting to another gateway. So, the proposed changes work and were tested for both BLE and Zigbee subdevices.
In my tests, I faced a weird behavior of my both BLE-capable gateways. If I detach a sub-device from it and then attach back, _sometimes_ they start reporting as online (as the reply for  `_sub_devs_query_task`) two different lists for odd and even requests: either with this detached/attached subdivce, or with the rest of subdevices. The gateways answer such a way until disconnect and reconnect. In logs, messages "Sub-device is absent" and "Sub-device is back" are shown, …
=> Handling removed/returned subdevices

custom_components/localtuya/cover.py
=> Fix cover state stuck when inverted and set position

custom_components/localtuya/__init__.py, custom_components/localtuya/coordinator.py
This is the only, rather cosmetic, problem faced during the whole August non-stop running.
Also found old typo error quickly reading your recent changes, yet to fully review them before applying the update to my current version.
=> Call disconnect() only once for offlined sub-device

custom_components/localtuya/switch.py
This is to fix "TypeError" durin HA startup.
```
File "/config/custom_components/localtuya/switch.py", line 82, in extra_state_attributes
attrs[ATTR_VOLTAGE] = self.dp_value(self._config[CONF_VOLTAGE]) / 10
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
=> TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

custom_components/localtuya/__init__.py
Merging your 2024.9.0 release into my HA, found two unused variables.
Though I'm not pretty sure if `dev.close()` tasks should be completed before the call to `async_unload_platforms`... But they never were before.
=> Cleanup after refactoring

custom_components/localtuya/cover.py
Hi xZetsubou!
I had a problem with my shutter in timed mode, when I opened it then paused it, then reopened it, the previous task async_stop_after_timeout paused the shutter again, because the previous task was never canceled when I paused the 1st time.
It's now fix !
=> Fix cover async_stop_after_timeout dead task

custom_components/localtuya/__init__.py
**The problem I was facing for a long time:**
Right after LocalTuya start or restart, some random entities may have Unavailable status, until they are updated from corresponding devices.
**The reason:**
The status of an entity can be updated by LocalTuya means only after the entity has been registered in HASS, i.e. after `LocalTuyaEntity.async_added_to_hass()` method was called, which registers `_update_handler()`. But `async_setup_entry()` _first_ created async tasks to connect to devices, _then_ waited for the first successful connect, and _only then_ called `hass.config_entries.async_forward_entry_setups()` which creates entities instances in HASS. `async_connect()`->`_make_connection()`  may change device's entities statuses, but the changes are not passed as they should.
With the …
=> Correct actions order in async_setup_entry

custom_components/localtuya/coordinator.py
8304b61368a6528d9f6cd386915c3a8f2e3814f2:
`_shutdown_entities` checks several properties and members that could be changed during connection process. So, to avoid possible race conditions, it is better to call it from the main thread loop of LocalTuya, rather than from HASS thread loop. Instead, a device's entities could be disabled right after successful re-connect. Frankly, I never experienced such a misbehavior.
70970c9b4308154672488bbfb3ac5a8d28f37559:
After several unsuccessful re-connect attempts, it is good to decide that the device is offline and increase delay between further attempts. Just like for sub-devices that were reported as offline by their gateways.
d0a95392f364fd6953c2a15b7e136f2d9c1207f5:
On close event, `_shutdown_entities`, actually, did nothing for low power and …
=> Avoid multithreading and other fixes

custom_components/localtuya/core/pytuya/__init__.py
Thinking about "listener exists for {seqno}" problem, I've put
```python
if msg.seqno + 1 < self.seqno:
self.warning(f"msg.seqno {msg.seqno} vs self.seqno {self.seqno} ack={ack} msg.cmd={msg.cmd}")
```
right above
https://github.com/xZetsubou/hass-localtuya/blob/2ed259f345fc9b5811aca048580e84d5d539e099/custom_components/localtuya/core/pytuya/__init__.py#L894-L897
and today morning found in the logs (for WiFi bulb):
```
2024-10-08 07:14:44.490 WARNING (MainThread) [custom_components.localtuya.core.pytuya] [bf0...sti - ГЛ2: LED BULB W5K] msg.seqno 47263 vs self.seqno 47265 ack=False msg.cmd=8
```
It means, if more than one requests are processed in parallel (remember `await` switches between tasks!), it is possible that `self.seqno` is updated from a delayed reply, and then some value is …
=> Don't update seqno from a delayed reply

custom_components/localtuya/core/pytuya/__init__.py
Another "cherry pick" from #363
=> Bug fix: self.transport shall not be None!

custom_components/localtuya/core/ha_entities/selects.py
Fixing typo of "Sielnt" to "Silent"
=> Fix Typo in Zone Attributes

custom_components/localtuya/coordinator.py, custom_components/localtuya/core/pytuya/__init__.py
I've started this set of changes when I realized that `TuyaDevice._call_on_close` permanently grows. Consider a WiFi battery powered T&H sensor that wakes up and sends measurements every 20 minutes, 3 times per hour. If it is configured with sleep time of 6 hours (21600 seconds), it generates 3 `_shutdown_entities` tasks per hour, 72 items in the `TuyaDevice._call_on_close` per day. Add here one `_new_entity_handler` per successful connect and `_async_reconnect` to re-connect, to have 3x72=216 items per day from one sensor alone, not counting other devices that may disconnect and re-connect. This is a memory leak.
Moreover, with this consideration, after 6 hours, 18 `_shutdown_entities` async tasks pilled up in the tasks queue, and then the queue always has at least 18 tasks to serve, …
=> Explicit tasks cancel

custom_components/localtuya/coordinator.py, custom_components/localtuya/core/pytuya/__init__.py
It is essential first to close the sub-devices, to make their `_is_closing==True`, and only then disconnect the gateway. There was my comment that you've removed. Now I revert your change and put back the comment.
=> Close order revert

custom_components/localtuya/fan.py
int conversion of string speed ranges provided by fan that led to below exception at HA start and hence deactivation of fan entities.
Exception in _update_handler when dispatching 'localtuya_bf753e0f5ece46fcb58mv4': ({'20': True, '22': 900, '23': 0, '60': False, '62': 1, '63': 'reverse', '64': 0},) Traceback (most recent call last): File "/config/custom_components/localtuya/entity.py", line 177, in _update_handler self.status_updated() ~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/localtuya/fan.py", line 240, in status_updated self._percentage = ranged_value_to_percentage( 
~~~~~~~~~~~~~~~~~~~~~~~~~~^ self._speed_range, int(current_speed) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 76, in ranged_value_to_percentage …
=> Fix fan.py

custom_components/localtuya/climate.py
related: #486 
- Ensure the preset DP is the same HVAC mode DP before check.
- The condition would ensure that if preset and HVAC share same DP to not update preset mode if HVAC changed. this made because if preset contains more HVAC modes that aren't supported by HA would give user ability to change it otherwise state would be stuck to the latest one and would require to change it to another one then back.
=> fix(climate): Preset mode always is null

custom_components/localtuya/remote.py, hacs.json
realted #421 
_note: 433.92 is the default frequency for learn command._
=> feat(remote): Add support for rf commands

documentation/docs/usage/configure_add_device.md, documentation/docs/usage/installation.md
"Installation integration" has a "Get authorization data" which leads to 404 now, because target document placed in the parent directory.
=> Fix broken link

custom_components/localtuya/climate.py
Add is_on property to check the state of device.
- This is related to #496 where if the on/off are string and usef if not both will return true, implement is_on to handle these cases as well
=> fix(climate): add is_on property to support all on/off state types

custom_components/localtuya/climate.py
This feature calculates HVAC Action (from HVACMode and target/current temperatures) if the device is unable to do it. 
Useful when you operate real device, like air-vales, heater, cooler, etc.
The upstream code contained some unnecessary lines and worked only with heating mode (as anything other climate stuff). 
1. However the CURRENT_* constants were converted to HVACMode, instead of HVACAction, so this should be corrected.
2. The code is also updated to support Fan/Dry/HeatCool modes.
=> perf(climate): Heuristic Action and fix heating

custom_components/localtuya/light.py
realted #499
Explain: due to refactor made in `Light fixes and BLE bulbs support #425`  the `self._hs` broke and no longer scale `sat` value to `100`
=> fix(light): brightness for encoded rgb bulbs

custom_components/localtuya/config_flow.py, custom_components/localtuya/core/cloud_api.py, custom_components/localtuya/diagnostics.py
Explanation: Due to the fact that this fork contains more features, especially auto-configure entities, with the help of the Tuya API, we retrieve the devices’ DPS codes. Based on these codes, we use them to configure the entities.
Currently, each device makes “3” API calls to retrieve all the DPS codes, including the ones that are missing in the official HA Tuya integration. The main issue was that these calls would happen every time the integration loaded, which caused delays in device connection. Specifically, when the call happened in the middle of the connection process, it would slow down the connection more than it should have.
Now, the changes in #471 have made these calls much faster (0.3s or less), and they no longer affect the connection.
- If one device is being configured, …
=> fix(cloud_api): remove unnecessary calls

.github/workflows/draft_release.yml
github revert process commit e.g. "Revert <reverted_commit>" which fails to parse due the missing colon
=> ci: ignore colon on prefix

custom_components/localtuya/coordinator.py, custom_components/localtuya/core/pytuya/__init__.py
I'm yet to find time to update to HA Core 2025.x, and to incorporate your many changes to LocalTuya :(
Meanwhile, I ran many tests with low performance HA server, and, as the result, these are related fixes. I suggest to read commit by commit: they all should be understandable. Yes, I saw all the fixed misbehaviors in real life!
Yes, I saw successful connects after 4.5 seconds. But, regardless, making `TIMEOUT_CONNECT` (was 3) less than `TIMEOUT_REPLY` has not much sense: usually connect is even longer process.
I've changed `HEARTBEAT_INTERVAL` to 8.3 because 83 is a big enough prime number. Making periodic tasks with periods of prime numbers decrease the chance of "crowded" periodic events across the whole system.
=> Fixes for low performance HA servers

custom_components/localtuya/coordinator.py
related: #517
Removed `localtuya_device_triggered` since it kinda doesn't makes sense while states_update exists.
`states_update` renamed to `status_update`
This may or may not fix the issue, however it will decrease the amount of events that being fired.
=> breaking_change(events): removed/rename events and improve events handler

custom_components/localtuya/coordinator.py, custom_components/localtuya/core/pytuya/__init__.py
Weak detection of absent sub-devices instead of fuzzy logic with delays:
The lists of offline/online subdevices are parsed and handled immediatelly. A device is considered as absent if it was not mentioned in either list, nor its DPs were updated, for at least two heartbeat periods.
`_connect_subdevices()` no longer checks for `SubdeviceState.ABSENT` because it is now weak state. It does not hurt to try to connect to a subdevice that may be absent anyway.
`pass` operator is intentional: to prevent an attempt to handle this case by a further developer who didn't read the comment in the pytuya.py.
Tested and proved to work.
=> Better handling of absent subdevices

.devcontainer/devcontainer.json, CONTRIBUTING.md
Adds a github codespaces 'quick start' approach, which is handy when you don't have a local environment.
Adds some suggested contributing guidelines, which may or may not be useful.
=> Add a basic dev container and contributing doc

custom_components/localtuya/remote.py
Adding support for sending raw IR codes (when device is not specified)
in order to enable other components like SmartIR to send codes they store on their end.
This allows for a very nice UI and easier management of large number of codes for different AC brands, as supported by SmartIR.
Tested on my machine and works nicely. 
This resolves many long standing request for integration between SmartIR and local-tuya.
=> Add support for sending raw IR codes via Tuya remote

custom_components/localtuya/coordinator.py, custom_components/localtuya/manifest.json
This is just workaround, for those who doesn't use the "events", events now will be ignored if no-one listen to it.
related to #517
=> perf: ignore fire event if no listeners

custom_components/localtuya/core/ha_entities/sensors.py, custom_components/localtuya/core/ha_entities/vacuums.py, custom_components/localtuya/vacuum.py, tests/test_vacuum.py
Home Assistant no longer has battery attribute in Vacuum entity, instead now user shall create seprated sensor entity for battery.
related: #706
REF: https://developers.home-assistant.io/blog/2025/07/02/vacuum-battery-properties-deprecated?_highlight=vacuum
=> refactor(vacuum): Remove battery attrbiute
