xZetsubou/hass-localtuya

- custom_components/localtuya/config_flow.py
- custom_components/localtuya/manifest.json
- custom_components/localtuya/strings.json
- custom_components/localtuya/translations/en.json
Explained in #1475
- Abort the config if account already configured!. Fix data remove if add duplicate.
- Change the category.
> Fix account duplicate and change category

- custom_components/localtuya/config_flow.py
closes #18 
Fix an issue happened in `mergeDevicesList` when there is more then 1 sub devices connected to same gateway
> fix an error when pulling sub-devices

- custom_components/localtuya/__init__.py
- Improvement connecting devices at startup.
> This also fix sub devices doesn't connect directly it takes 1min [reconnect check] to connect.
> fix devices setup connect devices [sub devices]

- custom_components/localtuya/config_flow.py
- Entities will be automatically removed when unchecked in edit device.
> Confi_Flow: Remove only unwanted entites in edit device.

- custom_components/localtuya/__init__.py
- custom_components/localtuya/common.py
- custom_components/localtuya/config_flow.py
- custom_components/localtuya/diagnostics.py
- custom_components/localtuya/services.yaml
> Calling back listener func in unload to unlisten. [ Fix multi reload calls ]
Keys:
- Multi Hubs support.
- Reconnect improvements `[make_connection]` .
- add GUI For `set_dp` service.
> Supports multi hubs and services GUI

- custom_components/localtuya/common.py
- custom_components/localtuya/config_flow.py
- custom_components/localtuya/discovery.py
- custom_components/localtuya/light.py
- custom_components/localtuya/pytuya/__init__.py
changes:
- Fix Music value in lights get reset each time edit device...
- Clarify errors messages when adding new hub
- fix bugs in light [ force int ]
- Fix product key reset when edit device can cause double reloading
input `-` or empty space in manual dps or reset DP field to remove values.
Fix discovering 3.5 devices in network.
Fix connecting to 3.5 devices
Main: 
Attempt to fix protocol `3.5`. closes #25, closes #30
- [1st]. adjust negotiate_session_key function
> Prepare 3.1.0

- custom_components/localtuya/cloud_api.py
- custom_components/localtuya/config_flow.py
- custom_components/localtuya/core/pytuya/__init__.py
* Manually: if device id found in cloud pulls info
* Manually: fields will restore to the last inputs if errors
* Improved catching errors when if connection fails
> Improve device connection `add device step` 

- custom_components/localtuya/common.py
- custom_components/localtuya/config_flow.py
- custom_components/localtuya/core/pytuya/__init__.py
* Fix: Fake gateway become unusable if node id not found.
* Fix: connection stuck if Fake gateway trying to reach disconnect sub device.
* Fix: Adding sub device will make sure fake gateway connected before use.
* Fix: loop re-connecting if sub device dc'd.
* Fix: Sub devices goes unavailable of fake gateway dc'd
fixes: #66
> Minor fixes sub devices

- custom_components/localtuya/alarm_control_panel.py
- custom_components/localtuya/const.py
- custom_components/localtuya/core/ha_entities/__init__.py
- custom_components/localtuya/core/ha_entities/base.py
- custom_components/localtuya/core/ha_entities/numbers.py
- custom_components/localtuya/core/ha_entities/selects.py
- custom_components/localtuya/core/ha_entities/sensors.py
- custom_components/localtuya/core/ha_entities/switches.py
- custom_components/localtuya/translations/ar.json
- custom_components/localtuya/translations/en.json
- custom_components/localtuya/translations/it.json
- custom_components/localtuya/translations/pl.json
- custom_components/localtuya/translations/pt-BR.json
> Add alarm support

- custom_components/localtuya/core/ha_entities/base.py
- custom_components/localtuya/core/ha_entities/switches.py
in automatic mode there isn't such switch while tuya cloud can share it
> Add PTZ Stop Switch in Smart Camera "sp" category

- custom_components/localtuya/config_flow.py
- custom_components/localtuya/core/cloud_api.py
Adding more regions for the api.
> Adding of EU and WE regions

- custom_components/localtuya/coordinator.py
This warning fills my log for WiFi T&H sensor. Obviously, the device is unreachable most of the time.
> Excess warning for low power devices

- custom_components/localtuya/__init__.py
Currently, the startup process connects to all the devices in no particular order. This approach has several drawbacks:
1. If a real gateway was added to LocalTuya, and it is connected after its sub-devices, then there are two connections to it: as a fake gateway and as a separate device. This produces additional uncontrolled (no delays between writes) load.
2. Most of sub-devices on the first call to `_make_connection` only add themselves to the `gateway.sub_devices`, then fail because the (fake) gateway is not connected yet. This is waste of time.
3. Theoretically, it is possible that no one of sub-devices would reach their  `_make_connection` in time, and their (fake) gateway would finish its connection with empty `sub_devices`, and will not call `start_sub_devices_heartbeat`. …
> Connect to devices in a specific order

- custom_components/localtuya/lock.py
> Fix the lock state inverted 

- custom_components/localtuya/core/ha_entities/__init__.py
This change allows the device to be added without an error. After that I can manually configure the min and max values.
> Handle empty range for tuya fan

- README.md
I believe this feature is good enough to deserve its own mention, what do you think?
> Add remote entity to features in README

- custom_components/localtuya/__init__.py
> feat: disconnect device on disable

- custom_components/localtuya/__init__.py
- custom_components/localtuya/coordinator.py
> pref: Include sub device on disable disconnection

- custom_components/localtuya/config_flow.py
> add possibilty to add manual dps in reconfigure step

- custom_components/localtuya/config_flow.py
- custom_components/localtuya/coordinator.py
- custom_components/localtuya/core/ha_entities/base.py
- custom_components/localtuya/core/ha_entities/lights.py
- custom_components/localtuya/entity.py
- custom_components/localtuya/light.py
This modified PR of #425 by @Lurker00 -- removed any dependence that require cloud to detect the type of bulb.
> feat: add support for BLE bulbs

- custom_components/localtuya/vacuum.py
> fix(vacuum): Updated deprecated constant

- custom_components/localtuya/light.py
- Drops deprecated constants.
- FIx map range method to give correct number.
- Use map range based on percent for brightness.
- Fix Temperature value are way off from Tuya APP.
- Set min default brightness to 10.
---
related #442
> fixes(light): remove deprecated constant and improve values convert

- custom_components/localtuya/core/ha_entities/covers.py
- custom_components/localtuya/cover.py
> feat(cover): handle bool state for covers

- custom_components/localtuya/climate.py
> feat(climate): handle string/number states

- custom_components/localtuya/light.py
> fix(light): map_range reverse

- custom_components/localtuya/climate.py
related #502
not this feature will auto enabled if no hvac_action DP is inserted.
> fix(climate): heuristic_action logic

- .github/workflows/ci.yml
- README.md
- custom_components/localtuya/__init__.py
- custom_components/localtuya/climate.py
- custom_components/localtuya/config_flow.py
- custom_components/localtuya/core/ha_entities/__init__.py
- custom_components/localtuya/core/ha_entities/base.py
- custom_components/localtuya/core/ha_entities/binary_sensors.py
- custom_components/localtuya/core/ha_entities/selects.py
- custom_components/localtuya/core/ha_entities/switches.py
- custom_components/localtuya/core/pytuya/__init__.py
- custom_components/localtuya/cover.py
- custom_components/localtuya/light.py
- custom_components/localtuya/remote.py
- custom_components/localtuya/templates/sample_2g_switch.yaml
- documentation/docs/auto_configure.md
- documentation/docs/faq/index.md
- documentation/docs/ha_events.md
- pylint.rc
- pyproject.toml
- requirements_test.txt
well this can be removed any time if it will interrupt the implementation due to Tuya Codes contains misspell words
> ci: add code spell and refactor ci workflow

- documentation/docs/index.md
> docs: fix usage broken link in overview

- custom_components/localtuya/climate.py
> fix(climate): convert current temperature when unit is celsius/fahrenheit

- custom_components/localtuya/binary_sensor.py
- custom_components/localtuya/const.py
- custom_components/localtuya/translations/en.json
> feat: add interval reset timer to set state off 

- custom_components/localtuya/climate.py
Reverts xZetsubou/hass-localtuya#541
> Revert "fix(climate): convert current temperature when unit is celsius/fahrenheit"

- custom_components/localtuya/core/cloud_api.py
Due to the fact that there's a chance of old method that can create 3 or more session which may broke requests, Create class to shared aiohttp session where it manage mass requests correctly.
> perf(cloud_api): Add shared aiohttp class session to manage requests

- custom_components/localtuya/binary_sensor.py
> fix(binary_sensor): reset state timer

- custom_components/localtuya/climate.py
- custom_components/localtuya/const.py
- custom_components/localtuya/translations/en.json
- documentation/docs/ha_events.md
> feat(climate): Add swings support

- custom_components/localtuya/__init__.py
Fix broken implementation from e05a8380fc0bf0c3589a37c449bd97fb2a456345
> fix: correct closing devices on shutdown

- custom_components/localtuya/translations/en.json
Accidentally added in the fan swing mode PR
> Update en.json - Fix trailing whitespace

- custom_components/localtuya/light.py
> fix(lights): `argument of type` error

- custom_components/localtuya/humidifier.py
> fix(humidifier): local variable modes error

- custom_components/localtuya/entity.py
- custom_components/localtuya/manifest.json
> fix(entity): device classes not configured

- custom_components/localtuya/__init__.py
Made these small changes a long ago...
> Spell and avoided unneeded operations

- custom_components/localtuya/translations/zh-Hans.json
feature(language): Add support for 简体中文 (Simplified Chinese)
> feature(language): Add support for 简体中文 (Simplified Chinese)

- custom_components/localtuya/translations/vi.json
feature(language): Add support for Vietnamese
> feature(language): Add support for Vietnamese
